// Auto-generated by make — do not edit
let buildVersion = "0.1.3"
let buildCommit = "7bed5c2"
let buildBranch = "main"
let buildDate = "2026-04-03 23:23:27 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
